services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
    # volumes:
    #   - ./data:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"

  mysql:
    platform: linux/x86_64 # Needed for Mac's on the M1 chip
    image: mysql:5
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

  postgres:
    image: postgres:11.3
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "${MSSQL_PORT}:1433"

  oracle:
    image: gvenzl/oracle-xe:21-slim
    platform: linux/amd64
    restart: always
    ports:
      - "${ORACLE_PORT}:1521" # Oracle Listener
      - "5500:5500" # Enterprise Manager Express
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      ORACLE_CHARACTERSET: "AL32UTF8"
    shm_size: "1g"