name: Trigger Docker Image Creation

on:
  workflow_run:
    workflows: [BoxLang Snapshots]
    types: [completed]
    branches:
      - "development"

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger Workflow for docker-bx Repo
        run: |
          # Set the required variables
          target_repo_owner="ortus-solutions-private"
          target_repo_name="docker-bx"
          target_branch="main"
          bx_version="1.0.0"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHA_WORKFLOW_DISPATCHER_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$target_repo_owner/$target_repo_name/actions/workflows/release.yml/dispatches \
            -d "{\"ref\": \"$target_branch\", \"inputs\": {\"version\": \"$bx_version\"}}"
      - name: Trigger Workflow for bx-aws-lambda Repo
        run: |
          # Set the required variables
          target_repo_owner="ortus-solutions-private"
          target_repo_name="bx-aws-lambda"
          target_branch="development"
          bx_version="1.0.0"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHA_WORKFLOW_DISPATCHER_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$target_repo_owner/$target_repo_name/actions/workflows/release.yml/dispatches \
            -d "{\"ref\": \"$target_branch\", \"inputs\": {\"version\": \"$bx_version\"}}"
